#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Distribute requests using a roundrobin algorithm
# Install and configure HAproxy on my lb-01 server.
sudo apt-get -y update
sudo apt-get -y install haproxy=1.6.\*
"
name = Endesew
server = 210747-web-02
" >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
service haproxy restart
