#!/usr/bin/env bash
# A bash script that displays "Best School" 10x and 'hi' after the 9th using while and if

counter=1

while [ $counter -le 10 ]
do
    echo "Best School"
    if [ $counter -eq 9 ]
    then
        echo "Hi"
    fi
    ((counter++))
done
