#!/usr/bin/env bash
# A bash script that displays at 4th china, 9th Japan &17th Italy

counter=1

while [ $counter -le 20 ]
do
  echo "$counter"
  case $counter in
    "4") echo "bad luck from China";;
    "9") echo "bad luck from Japan";;
    "17") echo "bad luck from Italy";;
  esac
  ((counter++ ))
done
