#!/usr/bin/env bash
# A bash script displays the content of the current directory in list format
# Only displays the part of the name after the first dash

mydictcontent=$(ls)

for list in $mydictcontent
do
  echo "$list" | cut -d '-' -f2
done
